
version: "3"
networks:
 Mariadb_PhpMyadmin:
    driver: bridge

services:
  db:
      image: mariadb
      container_name: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=Abc-mib123
          - MYSQL_DATABASE=Flower
      networks:
          - Mariadb_PhpMyadmin
      volumes:
          - ./database:/var/lib/mysql
      ports:
          - 3306:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      networks:
         - Mariadb_PhpMyadmin
      environment:
              #          - PMA_ARBITRARY=1
          - PMA_HOST=db
      restart: always
      ports:
          - 80:80
      links:
          - db
