version : '3'

networks:
  Mariadb_PhpMyadmin:
     driver: bridge

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
        - ./database:/var/lib/mysql
    networks:
        - Mariadb_PhpMyadmin
    ports:
        - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      #PMA_ARBITRARY: 1
    restart: always
    networks:
      - Mariadb_PhpMyadmin
    ports:
      - 80:80
