version: '3'

networks:
  wordpress:
     driver: bridge
     
services:
   wordpress:
     depends_on:
       - db
     image: wordpress
     container_name: wordpress
     volumes:
       - ./wordpress_data:/var/www/html
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
        - wordpress

   db:
     image: mysql:5.7
     container_name: db
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     ports:
      - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
      
     networks:
        - wordpress
